name: CI/CD

on:
  push:
    branches: [main]

jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.1
        cache: npm

    - name: Npm install
      run: npm install --quiet
      shell: bash

    - name: Deploy
      run: npm run deploy
      shell: bash
